// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace WebAPI_Project.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int St_Id { get; set; }

    [StringLength(50)]
    public string St_Fname { get; set; }

    [StringLength(10)]
    public string St_Lname { get; set; }

    [StringLength(100)]
    public string St_Address { get; set; }

    public int? St_Age { get; set; }

    public int? Dept_Id { get; set; }

    public int? St_super { get; set; }

    [ForeignKey("Dept_Id")]
    [InverseProperty("Students")]
    //[JsonIgnore] // to ignore some data dure sending the data (but using this way stoping me from retrive relative data always"not the best way")
    public virtual Department Dept { get; set; }

    [InverseProperty("St_superNavigation")]
    //[JsonIgnore] // u can't retrive it in all project not here only
    public virtual ICollection<Student> InverseSt_superNavigation { get; set; } = new List<Student>();

    [ForeignKey("St_super")]
    [InverseProperty("InverseSt_superNavigation")]
    //[JsonIgnore] // also u can ignore properety like Dept_Id
    public virtual Student St_superNavigation { get; set; }

    [InverseProperty("St")]
    //[JsonIgnore] // u can specify it's condition like "whenWritingDefualt" and "whenWritingNull" (it means preform it on these cases only)
    public virtual ICollection<Stud_Course> Stud_Courses { get; set; } = new List<Stud_Course>();
}